/**
 * Search over the site index: tokenising, matching and ranking.
 *
 * The index is generated by `src/plugins/search-index.js`. This module turns
 * it into an inverted index once, then answers each query by scoring the
 * sections every query term can be found in.
 */

export type Kind = 'd' | 'r' | 'c' | 'p'

/** The file as shipped: pages, and sections that point at their page. */
export type RawIndex = {
  v: 1
  p: [url: string, title: string, kind: Kind, group: string][]
  s: [page: number, id: string, heading: string, text: string, code: string][]
}

export type Entry = {
  id: number
  url: string
  /** Anchor inside the page; empty for the page itself. */
  anchor: string
  /** What the result is called: the section heading, or the page title. */
  label: string
  /** The page the section belongs to. */
  page: string
  kind: Kind
  /** Where the page sits in the documentation, e.g. "API reference". */
  group: string
  text: string
  code: string
  isPage: boolean
}

export type Prepared = {
  entries: Entry[]
  /** Every distinct token, with the places it occurs. */
  vocabulary: [token: string, postings: Int32Array][]
}

export type Result = {
  entry: Entry
  score: number
  /** Strings to highlight in the label and excerpt, lower-cased. */
  needles: string[]
  excerpt: string
}

export type Group = { kind: Kind; title: string; results: Result[] }

export const kindTitles: Record<Kind, string> = {
  d: 'Docs',
  r: 'Reference',
  c: 'Components',
  p: 'Pages',
}

// Where a token was found. A posting packs `entry * 4 + field`.
const LABEL = 0
const PAGE = 1
const CODE = 2
const BODY = 3

/** Title beats heading beats code identifier beats body text. */
const TITLE_WEIGHT = 12
const HEADING_WEIGHT = 9
const PAGE_WEIGHT = 2.5
const CODE_WEIGHT = 5
const BODY_WEIGHT = 1.5

/** How well a query term matches an indexed token. */
const EXACT = 1
const PREFIX = 0.75
const SUBSTRING = 0.4
const TYPO = 0.3

/** A single edit is tolerated only on terms at least this long. */
const TYPO_MIN_LENGTH = 5
const MAX_TERMS = 8
const MAX_PER_PAGE = 3
const MAX_PER_GROUP = 6
const MAX_RESULTS = 18
const EXCERPT_LENGTH = 132

const WORD = /[@$]?[A-Za-z0-9_]+/g

/**
 * Tokens of a piece of text. An identifier is indexed whole and by its
 * camel-case parts, so `createElements` is found by "createelements",
 * "create" and "elements"; a sigil is optional (`@media` and `media`).
 */
function tokens(text: string, into: Set<string>) {
  for (const match of text.matchAll(WORD)) {
    const word = match[0]
    const bare = word.replace(/^[@$]/, '')
    if (!bare) continue
    into.add(word.toLowerCase())
    if (bare !== word) into.add(bare.toLowerCase())
    if (/[a-z0-9][A-Z]|_/.test(bare))
      for (const part of bare.split(/(?<=[a-z0-9])(?=[A-Z])|_/))
        if (part.length > 1) into.add(part.toLowerCase())
  }
}

/** Query terms: lower-cased words, sigils kept, repeats dropped. */
export function queryTerms(query: string): string[] {
  const found = new Set<string>()
  for (const match of query.matchAll(WORD)) found.add(match[0].toLowerCase())
  return [...found].slice(0, MAX_TERMS)
}

export function prepare(raw: RawIndex): Prepared {
  const entries: Entry[] = raw.s.map(
    ([page, id, heading, text, code], index) => {
      const [url, title, kind, group] = raw.p[page] ?? ['/', '', 'p', '']
      return {
        id: index,
        url,
        anchor: id,
        label: heading || title,
        page: title,
        kind,
        group,
        text,
        code,
        isPage: !heading,
      }
    },
  )

  const postings = new Map<string, number[]>()
  const bag = new Set<string>()
  const add = (entry: Entry, field: number, text: string) => {
    if (!text) return
    bag.clear()
    tokens(text, bag)
    for (const token of bag) {
      const list = postings.get(token)
      if (list) list.push(entry.id * 4 + field)
      else postings.set(token, [entry.id * 4 + field])
    }
  }
  for (const entry of entries) {
    add(entry, LABEL, entry.label)
    if (!entry.isPage) add(entry, PAGE, entry.page)
    add(entry, CODE, entry.code)
    add(entry, BODY, entry.text)
  }
  return {
    entries,
    vocabulary: [...postings].map(([token, list]) => [
      token,
      Int32Array.from(list),
    ]),
  }
}

/** True when `a` becomes `b` by one insertion, deletion, substitution or swap. */
function oneEditApart(a: string, b: string) {
  const la = a.length
  const lb = b.length
  if (Math.abs(la - lb) > 1 || a === b) return false
  let i = 0
  while (i < la && i < lb && a[i] === b[i]) i++
  if (la === lb) {
    // Substitution, or two neighbouring characters swapped.
    if (a.slice(i + 1) === b.slice(i + 1)) return true
    return (
      a[i] === b[i + 1] &&
      a[i + 1] === b[i] &&
      a.slice(i + 2) === b.slice(i + 2)
    )
  }
  const [long, short] = la > lb ? [a, b] : [b, a]
  return long.slice(i + 1) === short.slice(i)
}

function quality(term: string, token: string) {
  if (token === term) return EXACT
  if (token.startsWith(term)) return PREFIX
  if (term.length >= 3 && token.includes(term)) return SUBSTRING
  // A typo rarely changes the first letter; requiring it keeps noise down.
  if (
    term.length >= TYPO_MIN_LENGTH &&
    token[0] === term[0] &&
    oneEditApart(term, token)
  )
    return TYPO
  return 0
}

const normalise = (text: string) =>
  text.toLowerCase().replace(/\s+/g, ' ').trim()

function fieldWeight(entry: Entry, field: number) {
  if (field === LABEL) return entry.isPage ? TITLE_WEIGHT : HEADING_WEIGHT
  if (field === PAGE) return PAGE_WEIGHT
  return field === CODE ? CODE_WEIGHT : BODY_WEIGHT
}

function excerptOf(text: string, needles: string[]) {
  if (!text) return ''
  const lower = text.toLowerCase()
  let at = -1
  for (const needle of needles) {
    const index = lower.indexOf(needle)
    if (index >= 0 && (at < 0 || index < at)) at = index
  }
  if (at < 0 || at < EXCERPT_LENGTH * 0.6)
    return text.length > EXCERPT_LENGTH
      ? `${text.slice(0, EXCERPT_LENGTH).trimEnd()}…`
      : text
  // Start a few words before the match, on a word boundary.
  const from = text.indexOf(' ', Math.max(0, at - 40)) + 1
  const slice = text.slice(from, from + EXCERPT_LENGTH)
  return `…${slice.trimEnd()}${from + EXCERPT_LENGTH < text.length ? '…' : ''}`
}

/**
 * Ranked results for a query. Every term must match somewhere in a section
 * (its heading, its page title, its code identifiers or its text). The score
 * is the sum of each term's best match, weighted by where it was found, plus
 * bonuses for the exact phrase and for a heading the query covers.
 */
export function search(index: Prepared, query: string): Result[] {
  const terms = queryTerms(query)
  if (terms.length === 0) return []
  const count = index.entries.length
  const total = new Float32Array(count)
  const matched = new Uint8Array(count)
  /** Per term: how much of the score came from the label, for coverage. */
  const labelHits = new Uint8Array(count)
  const needles = new Set<string>(terms)

  terms.forEach((term, position) => {
    const best = new Float32Array(count)
    const inLabel = new Uint8Array(count)
    for (const [token, postings] of index.vocabulary) {
      const q = quality(term, token)
      if (q === 0) continue
      if (q === TYPO) needles.add(token)
      for (const posting of postings) {
        const id = posting >> 2
        const field = posting & 3
        const entry = index.entries[id]
        if (!entry) continue
        const score = q * fieldWeight(entry, field)
        if (score > (best[id] ?? 0)) best[id] = score
        if (field === LABEL && q >= PREFIX) inLabel[id] = 1
      }
    }
    for (let id = 0; id < count; id++) {
      const score = best[id] ?? 0
      if (score === 0) continue
      // Only sections that matched every earlier term stay in the running.
      if ((matched[id] ?? 0) !== position) continue
      matched[id] = position + 1
      total[id] = (total[id] ?? 0) + score
      labelHits[id] = (labelHits[id] ?? 0) + (inLabel[id] ?? 0)
    }
  })

  const phrase = normalise(query)
  const needleList = [...needles].sort((a, b) => b.length - a.length)
  const results: Result[] = []
  for (const entry of index.entries) {
    if (matched[entry.id] !== terms.length) continue
    let score = total[entry.id] ?? 0
    const label = normalise(entry.label)
    if (label === phrase) score += 14
    else if (label.includes(phrase)) score += 8
    if (terms.length > 1) {
      if (entry.code.toLowerCase().includes(phrase)) score += 4
      if (entry.text.toLowerCase().includes(phrase)) score += 3
    }
    // A heading the query covers outranks a longer heading that contains it.
    const labelWords = label.split(/[^a-z0-9@$_]+/).filter(Boolean).length
    if (labelWords > 0)
      score += 4 * Math.min(1, (labelHits[entry.id] ?? 0) / labelWords)
    // A page outranks its own sections when both match equally.
    if (entry.isPage) score *= 1.15
    results.push({
      entry,
      score,
      needles: needleList,
      excerpt: excerptOf(entry.text, [phrase, ...needleList]),
    })
  }
  // Index order breaks ties, so equal scores always list the same way.
  results.sort((a, b) => b.score - a.score || a.entry.id - b.entry.id)

  const perPage = new Map<string, number>()
  return results.filter((result) => {
    const seen = perPage.get(result.entry.url) ?? 0
    perPage.set(result.entry.url, seen + 1)
    return seen < MAX_PER_PAGE
  })
}

/** Results by kind, best group first, cut to what a palette can show. */
export function group(results: Result[]): Group[] {
  const groups = new Map<Kind, Result[]>()
  let shown = 0
  for (const result of results) {
    if (shown === MAX_RESULTS) break
    const list = groups.get(result.entry.kind) ?? []
    if (list.length === MAX_PER_GROUP) continue
    list.push(result)
    groups.set(result.entry.kind, list)
    shown++
  }
  return [...groups].map(([kind, list]) => ({
    kind,
    title: kindTitles[kind],
    results: list,
  }))
}

/** Splits text into plain and matched runs for highlighting. */
export function highlight(
  text: string,
  needles: string[],
): { text: string; hit: boolean }[] {
  const lower = text.toLowerCase()
  const ranges: [number, number][] = []
  for (const needle of needles) {
    if (!needle) continue
    let from = lower.indexOf(needle)
    while (from >= 0) {
      ranges.push([from, from + needle.length])
      from = lower.indexOf(needle, from + needle.length)
    }
  }
  if (ranges.length === 0) return [{ text, hit: false }]
  ranges.sort((a, b) => a[0] - b[0])
  const parts: { text: string; hit: boolean }[] = []
  let cursor = 0
  for (const [start, end] of ranges) {
    if (end <= cursor) continue
    const from = Math.max(start, cursor)
    if (from > cursor)
      parts.push({ text: text.slice(cursor, from), hit: false })
    parts.push({ text: text.slice(from, end), hit: true })
    cursor = end
  }
  if (cursor < text.length) parts.push({ text: text.slice(cursor), hit: false })
  return parts
}
