import { stylesheet } from '../system.ts'

export const dialogStyles = stylesheet({
  // No `flow` here: a closed <dialog> must keep the browser's `display: none`.
  Root: {
    reset: 'dialog',
    measure: 'dialog',
    pad: 0,
    type: 'body',
    fill: 'overlay',
    ink: 'default',
    edge: 'panel',
    corner: 'panel',
    depth: 'overlay',
    frost: 'surface',
    native: 'dialog',
  },
  Form: { flow: 'column' },
  Head: {
    flow: 'row',
    align: 'center',
    justify: 'between',
    gap: 2,
    padX: 4,
    padY: 3,
    fill: 'head',
    ink: 'on-head',
    edge: 'rule',
  },
  Title: { $kind: 'text', type: 'title' },
  Body: { flow: 'column', gap: 4, pad: 4 },
  Foot: {
    flow: 'wrap',
    justify: 'end',
    gap: 3,
    padX: 4,
    padY: 3,
    edge: 'rule-top',
  },
})

export const menuStyles = stylesheet({
  Anchor: { flow: 'block', place: 'origin' },
  Trigger: {
    $kind: 'pressable',
    reset: 'control',
    flow: 'inline',
    align: 'center',
    gap: 2,
    pad: 0.5,
    type: 'control',
    fill: 'none',
    ink: 'on-bar',
    edge: 'none',
    corner: 'pill',
    ':focus-visible': { focus: 'ring' },
  },
  Menu: {
    place: 'menu',
    measure: 'menu',
    flow: 'column',
    gap: 0.5,
    pad: 1,
    fill: 'overlay',
    ink: 'default',
    edge: 'panel',
    corner: 'panel',
    depth: 'overlay',
    frost: 'surface',
  },
  // Who is signed in, above the actions.
  Label: { flow: 'column', padX: 3, padY: 2, edge: 'rule' },
  Name: { $kind: 'text', weight: 'strong', ink: 'strong' },
  Detail: { $kind: 'text', type: 'small', ink: 'muted' },
  Item: {
    $kind: 'pressable',
    reset: 'control',
    flow: 'row',
    flex: 'full',
    padX: 3,
    padY: 2,
    textAlign: 'left',
    type: 'body',
    fill: 'none',
    ink: 'default',
    edge: 'none',
    corner: 'inner',
    ':hover': { fill: 'selected', ink: 'on-selected' },
    ':focus-visible': { fill: 'selected', ink: 'on-selected' },
  },
})

export const toastStyles = stylesheet({
  // In the flow, after the content, so it never covers a control.
  Dock: { flow: 'row', justify: 'end' },
  Root: {
    flow: 'row',
    align: 'center',
    gap: 3,
    padX: 4,
    padY: 2,
    fill: 'overlay',
    ink: 'default',
    edge: 'panel',
    corner: 'panel',
    depth: 'overlay',
    frost: 'surface',
  },
  Mark: { size: 'swatch', fill: 'accent', corner: 'pill' },
  Text: { $kind: 'text', weight: 'strong' },
})
