/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesThemingRouteImport } from './routes/guides/theming'
import { Route as GuidesReactWebRouteImport } from './routes/guides/react-web'
import { Route as GuidesReactNativeRouteImport } from './routes/guides/react-native'
import { Route as GuidesInteractiveRouteImport } from './routes/guides/interactive'
import { Route as ApiVariantsRouteImport } from './routes/api/variants'
import { Route as ApiUseStylesRouteImport } from './routes/api/use-styles'
import { Route as ApiStylesheetRouteImport } from './routes/api/stylesheet'
import { Route as ApiMediaQueriesRouteImport } from './routes/api/media-queries'
import { Route as ApiDefineSystemRouteImport } from './routes/api/define-system'

const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesThemingRoute = GuidesThemingRouteImport.update({
  id: '/guides/theming',
  path: '/guides/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesReactWebRoute = GuidesReactWebRouteImport.update({
  id: '/guides/react-web',
  path: '/guides/react-web',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesReactNativeRoute = GuidesReactNativeRouteImport.update({
  id: '/guides/react-native',
  path: '/guides/react-native',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesInteractiveRoute = GuidesInteractiveRouteImport.update({
  id: '/guides/interactive',
  path: '/guides/interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVariantsRoute = ApiVariantsRouteImport.update({
  id: '/api/variants',
  path: '/api/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUseStylesRoute = ApiUseStylesRouteImport.update({
  id: '/api/use-styles',
  path: '/api/use-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStylesheetRoute = ApiStylesheetRouteImport.update({
  id: '/api/stylesheet',
  path: '/api/stylesheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaQueriesRoute = ApiMediaQueriesRouteImport.update({
  id: '/api/media-queries',
  path: '/api/media-queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDefineSystemRoute = ApiDefineSystemRouteImport.update({
  id: '/api/define-system',
  path: '/api/define-system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/api/define-system': typeof ApiDefineSystemRoute
  '/api/media-queries': typeof ApiMediaQueriesRoute
  '/api/stylesheet': typeof ApiStylesheetRoute
  '/api/use-styles': typeof ApiUseStylesRoute
  '/api/variants': typeof ApiVariantsRoute
  '/guides/interactive': typeof GuidesInteractiveRoute
  '/guides/react-native': typeof GuidesReactNativeRoute
  '/guides/react-web': typeof GuidesReactWebRoute
  '/guides/theming': typeof GuidesThemingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/api/define-system': typeof ApiDefineSystemRoute
  '/api/media-queries': typeof ApiMediaQueriesRoute
  '/api/stylesheet': typeof ApiStylesheetRoute
  '/api/use-styles': typeof ApiUseStylesRoute
  '/api/variants': typeof ApiVariantsRoute
  '/guides/interactive': typeof GuidesInteractiveRoute
  '/guides/react-native': typeof GuidesReactNativeRoute
  '/guides/react-web': typeof GuidesReactWebRoute
  '/guides/theming': typeof GuidesThemingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/api/define-system': typeof ApiDefineSystemRoute
  '/api/media-queries': typeof ApiMediaQueriesRoute
  '/api/stylesheet': typeof ApiStylesheetRoute
  '/api/use-styles': typeof ApiUseStylesRoute
  '/api/variants': typeof ApiVariantsRoute
  '/guides/interactive': typeof GuidesInteractiveRoute
  '/guides/react-native': typeof GuidesReactNativeRoute
  '/guides/react-web': typeof GuidesReactWebRoute
  '/guides/theming': typeof GuidesThemingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concepts'
    | '/api/define-system'
    | '/api/media-queries'
    | '/api/stylesheet'
    | '/api/use-styles'
    | '/api/variants'
    | '/guides/interactive'
    | '/guides/react-native'
    | '/guides/react-web'
    | '/guides/theming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concepts'
    | '/api/define-system'
    | '/api/media-queries'
    | '/api/stylesheet'
    | '/api/use-styles'
    | '/api/variants'
    | '/guides/interactive'
    | '/guides/react-native'
    | '/guides/react-web'
    | '/guides/theming'
  id:
    | '__root__'
    | '/'
    | '/concepts'
    | '/api/define-system'
    | '/api/media-queries'
    | '/api/stylesheet'
    | '/api/use-styles'
    | '/api/variants'
    | '/guides/interactive'
    | '/guides/react-native'
    | '/guides/react-web'
    | '/guides/theming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptsRoute: typeof ConceptsRoute
  ApiDefineSystemRoute: typeof ApiDefineSystemRoute
  ApiMediaQueriesRoute: typeof ApiMediaQueriesRoute
  ApiStylesheetRoute: typeof ApiStylesheetRoute
  ApiUseStylesRoute: typeof ApiUseStylesRoute
  ApiVariantsRoute: typeof ApiVariantsRoute
  GuidesInteractiveRoute: typeof GuidesInteractiveRoute
  GuidesReactNativeRoute: typeof GuidesReactNativeRoute
  GuidesReactWebRoute: typeof GuidesReactWebRoute
  GuidesThemingRoute: typeof GuidesThemingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/theming': {
      id: '/guides/theming'
      path: '/guides/theming'
      fullPath: '/guides/theming'
      preLoaderRoute: typeof GuidesThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/react-web': {
      id: '/guides/react-web'
      path: '/guides/react-web'
      fullPath: '/guides/react-web'
      preLoaderRoute: typeof GuidesReactWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/react-native': {
      id: '/guides/react-native'
      path: '/guides/react-native'
      fullPath: '/guides/react-native'
      preLoaderRoute: typeof GuidesReactNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/interactive': {
      id: '/guides/interactive'
      path: '/guides/interactive'
      fullPath: '/guides/interactive'
      preLoaderRoute: typeof GuidesInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/variants': {
      id: '/api/variants'
      path: '/api/variants'
      fullPath: '/api/variants'
      preLoaderRoute: typeof ApiVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/use-styles': {
      id: '/api/use-styles'
      path: '/api/use-styles'
      fullPath: '/api/use-styles'
      preLoaderRoute: typeof ApiUseStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stylesheet': {
      id: '/api/stylesheet'
      path: '/api/stylesheet'
      fullPath: '/api/stylesheet'
      preLoaderRoute: typeof ApiStylesheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-queries': {
      id: '/api/media-queries'
      path: '/api/media-queries'
      fullPath: '/api/media-queries'
      preLoaderRoute: typeof ApiMediaQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/define-system': {
      id: '/api/define-system'
      path: '/api/define-system'
      fullPath: '/api/define-system'
      preLoaderRoute: typeof ApiDefineSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptsRoute: ConceptsRoute,
  ApiDefineSystemRoute: ApiDefineSystemRoute,
  ApiMediaQueriesRoute: ApiMediaQueriesRoute,
  ApiStylesheetRoute: ApiStylesheetRoute,
  ApiUseStylesRoute: ApiUseStylesRoute,
  ApiVariantsRoute: ApiVariantsRoute,
  GuidesInteractiveRoute: GuidesInteractiveRoute,
  GuidesReactNativeRoute: GuidesReactNativeRoute,
  GuidesReactWebRoute: GuidesReactWebRoute,
  GuidesThemingRoute: GuidesThemingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
