/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LabRouteImport } from './routes/lab'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as UiRouteRouteImport } from './routes/ui/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UiIndexRouteImport } from './routes/ui/index'
import { Route as UiComponentRouteImport } from './routes/ui/$component'
import { Route as LearnTopicRouteImport } from './routes/learn/$topic'
import { Route as GuidesThemingRouteImport } from './routes/guides/theming'
import { Route as GuidesSsrRouteImport } from './routes/guides/ssr'
import { Route as GuidesReactWebRouteImport } from './routes/guides/react-web'
import { Route as GuidesReactNativeRouteImport } from './routes/guides/react-native'
import { Route as GuidesOverridesRouteImport } from './routes/guides/overrides'
import { Route as GuidesInteractiveRouteImport } from './routes/guides/interactive'
import { Route as ApiVariantsRouteImport } from './routes/api/variants'
import { Route as ApiUseStylesRouteImport } from './routes/api/use-styles'
import { Route as ApiStylesheetRouteImport } from './routes/api/stylesheet'
import { Route as ApiMediaQueriesRouteImport } from './routes/api/media-queries'
import { Route as ApiDefineSystemRouteImport } from './routes/api/define-system'
import { Route as ApiConditionsRouteImport } from './routes/api/conditions'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRouteRoute = UiRouteRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiIndexRoute = UiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UiRouteRoute,
} as any)
const UiComponentRoute = UiComponentRouteImport.update({
  id: '/$component',
  path: '/$component',
  getParentRoute: () => UiRouteRoute,
} as any)
const LearnTopicRoute = LearnTopicRouteImport.update({
  id: '/learn/$topic',
  path: '/learn/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesThemingRoute = GuidesThemingRouteImport.update({
  id: '/guides/theming',
  path: '/guides/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSsrRoute = GuidesSsrRouteImport.update({
  id: '/guides/ssr',
  path: '/guides/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesReactWebRoute = GuidesReactWebRouteImport.update({
  id: '/guides/react-web',
  path: '/guides/react-web',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesReactNativeRoute = GuidesReactNativeRouteImport.update({
  id: '/guides/react-native',
  path: '/guides/react-native',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesOverridesRoute = GuidesOverridesRouteImport.update({
  id: '/guides/overrides',
  path: '/guides/overrides',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesInteractiveRoute = GuidesInteractiveRouteImport.update({
  id: '/guides/interactive',
  path: '/guides/interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVariantsRoute = ApiVariantsRouteImport.update({
  id: '/api/variants',
  path: '/api/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUseStylesRoute = ApiUseStylesRouteImport.update({
  id: '/api/use-styles',
  path: '/api/use-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStylesheetRoute = ApiStylesheetRouteImport.update({
  id: '/api/stylesheet',
  path: '/api/stylesheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaQueriesRoute = ApiMediaQueriesRouteImport.update({
  id: '/api/media-queries',
  path: '/api/media-queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDefineSystemRoute = ApiDefineSystemRouteImport.update({
  id: '/api/define-system',
  path: '/api/define-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConditionsRoute = ApiConditionsRouteImport.update({
  id: '/api/conditions',
  path: '/api/conditions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ui': typeof UiRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/concepts': typeof ConceptsRoute
  '/examples': typeof ExamplesRoute
  '/explore': typeof ExploreRoute
  '/getting-started': typeof GettingStartedRoute
  '/lab': typeof LabRoute
  '/playground': typeof PlaygroundRoute
  '/themes': typeof ThemesRoute
  '/api/conditions': typeof ApiConditionsRoute
  '/api/define-system': typeof ApiDefineSystemRoute
  '/api/media-queries': typeof ApiMediaQueriesRoute
  '/api/stylesheet': typeof ApiStylesheetRoute
  '/api/use-styles': typeof ApiUseStylesRoute
  '/api/variants': typeof ApiVariantsRoute
  '/guides/interactive': typeof GuidesInteractiveRoute
  '/guides/overrides': typeof GuidesOverridesRoute
  '/guides/react-native': typeof GuidesReactNativeRoute
  '/guides/react-web': typeof GuidesReactWebRoute
  '/guides/ssr': typeof GuidesSsrRoute
  '/guides/theming': typeof GuidesThemingRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/ui/$component': typeof UiComponentRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/concepts': typeof ConceptsRoute
  '/examples': typeof ExamplesRoute
  '/explore': typeof ExploreRoute
  '/getting-started': typeof GettingStartedRoute
  '/lab': typeof LabRoute
  '/playground': typeof PlaygroundRoute
  '/themes': typeof ThemesRoute
  '/api/conditions': typeof ApiConditionsRoute
  '/api/define-system': typeof ApiDefineSystemRoute
  '/api/media-queries': typeof ApiMediaQueriesRoute
  '/api/stylesheet': typeof ApiStylesheetRoute
  '/api/use-styles': typeof ApiUseStylesRoute
  '/api/variants': typeof ApiVariantsRoute
  '/guides/interactive': typeof GuidesInteractiveRoute
  '/guides/overrides': typeof GuidesOverridesRoute
  '/guides/react-native': typeof GuidesReactNativeRoute
  '/guides/react-web': typeof GuidesReactWebRoute
  '/guides/ssr': typeof GuidesSsrRoute
  '/guides/theming': typeof GuidesThemingRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/ui/$component': typeof UiComponentRoute
  '/ui': typeof UiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ui': typeof UiRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/concepts': typeof ConceptsRoute
  '/examples': typeof ExamplesRoute
  '/explore': typeof ExploreRoute
  '/getting-started': typeof GettingStartedRoute
  '/lab': typeof LabRoute
  '/playground': typeof PlaygroundRoute
  '/themes': typeof ThemesRoute
  '/api/conditions': typeof ApiConditionsRoute
  '/api/define-system': typeof ApiDefineSystemRoute
  '/api/media-queries': typeof ApiMediaQueriesRoute
  '/api/stylesheet': typeof ApiStylesheetRoute
  '/api/use-styles': typeof ApiUseStylesRoute
  '/api/variants': typeof ApiVariantsRoute
  '/guides/interactive': typeof GuidesInteractiveRoute
  '/guides/overrides': typeof GuidesOverridesRoute
  '/guides/react-native': typeof GuidesReactNativeRoute
  '/guides/react-web': typeof GuidesReactWebRoute
  '/guides/ssr': typeof GuidesSsrRoute
  '/guides/theming': typeof GuidesThemingRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/ui/$component': typeof UiComponentRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ui'
    | '/changelog'
    | '/concepts'
    | '/examples'
    | '/explore'
    | '/getting-started'
    | '/lab'
    | '/playground'
    | '/themes'
    | '/api/conditions'
    | '/api/define-system'
    | '/api/media-queries'
    | '/api/stylesheet'
    | '/api/use-styles'
    | '/api/variants'
    | '/guides/interactive'
    | '/guides/overrides'
    | '/guides/react-native'
    | '/guides/react-web'
    | '/guides/ssr'
    | '/guides/theming'
    | '/learn/$topic'
    | '/ui/$component'
    | '/ui/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/concepts'
    | '/examples'
    | '/explore'
    | '/getting-started'
    | '/lab'
    | '/playground'
    | '/themes'
    | '/api/conditions'
    | '/api/define-system'
    | '/api/media-queries'
    | '/api/stylesheet'
    | '/api/use-styles'
    | '/api/variants'
    | '/guides/interactive'
    | '/guides/overrides'
    | '/guides/react-native'
    | '/guides/react-web'
    | '/guides/ssr'
    | '/guides/theming'
    | '/learn/$topic'
    | '/ui/$component'
    | '/ui'
  id:
    | '__root__'
    | '/'
    | '/ui'
    | '/changelog'
    | '/concepts'
    | '/examples'
    | '/explore'
    | '/getting-started'
    | '/lab'
    | '/playground'
    | '/themes'
    | '/api/conditions'
    | '/api/define-system'
    | '/api/media-queries'
    | '/api/stylesheet'
    | '/api/use-styles'
    | '/api/variants'
    | '/guides/interactive'
    | '/guides/overrides'
    | '/guides/react-native'
    | '/guides/react-web'
    | '/guides/ssr'
    | '/guides/theming'
    | '/learn/$topic'
    | '/ui/$component'
    | '/ui/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UiRouteRoute: typeof UiRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ConceptsRoute: typeof ConceptsRoute
  ExamplesRoute: typeof ExamplesRoute
  ExploreRoute: typeof ExploreRoute
  GettingStartedRoute: typeof GettingStartedRoute
  LabRoute: typeof LabRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ThemesRoute: typeof ThemesRoute
  ApiConditionsRoute: typeof ApiConditionsRoute
  ApiDefineSystemRoute: typeof ApiDefineSystemRoute
  ApiMediaQueriesRoute: typeof ApiMediaQueriesRoute
  ApiStylesheetRoute: typeof ApiStylesheetRoute
  ApiUseStylesRoute: typeof ApiUseStylesRoute
  ApiVariantsRoute: typeof ApiVariantsRoute
  GuidesInteractiveRoute: typeof GuidesInteractiveRoute
  GuidesOverridesRoute: typeof GuidesOverridesRoute
  GuidesReactNativeRoute: typeof GuidesReactNativeRoute
  GuidesReactWebRoute: typeof GuidesReactWebRoute
  GuidesSsrRoute: typeof GuidesSsrRoute
  GuidesThemingRoute: typeof GuidesThemingRoute
  LearnTopicRoute: typeof LearnTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/': {
      id: '/ui/'
      path: '/'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexRouteImport
      parentRoute: typeof UiRouteRoute
    }
    '/ui/$component': {
      id: '/ui/$component'
      path: '/$component'
      fullPath: '/ui/$component'
      preLoaderRoute: typeof UiComponentRouteImport
      parentRoute: typeof UiRouteRoute
    }
    '/learn/$topic': {
      id: '/learn/$topic'
      path: '/learn/$topic'
      fullPath: '/learn/$topic'
      preLoaderRoute: typeof LearnTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/theming': {
      id: '/guides/theming'
      path: '/guides/theming'
      fullPath: '/guides/theming'
      preLoaderRoute: typeof GuidesThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/ssr': {
      id: '/guides/ssr'
      path: '/guides/ssr'
      fullPath: '/guides/ssr'
      preLoaderRoute: typeof GuidesSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/react-web': {
      id: '/guides/react-web'
      path: '/guides/react-web'
      fullPath: '/guides/react-web'
      preLoaderRoute: typeof GuidesReactWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/react-native': {
      id: '/guides/react-native'
      path: '/guides/react-native'
      fullPath: '/guides/react-native'
      preLoaderRoute: typeof GuidesReactNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/overrides': {
      id: '/guides/overrides'
      path: '/guides/overrides'
      fullPath: '/guides/overrides'
      preLoaderRoute: typeof GuidesOverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/interactive': {
      id: '/guides/interactive'
      path: '/guides/interactive'
      fullPath: '/guides/interactive'
      preLoaderRoute: typeof GuidesInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/variants': {
      id: '/api/variants'
      path: '/api/variants'
      fullPath: '/api/variants'
      preLoaderRoute: typeof ApiVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/use-styles': {
      id: '/api/use-styles'
      path: '/api/use-styles'
      fullPath: '/api/use-styles'
      preLoaderRoute: typeof ApiUseStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stylesheet': {
      id: '/api/stylesheet'
      path: '/api/stylesheet'
      fullPath: '/api/stylesheet'
      preLoaderRoute: typeof ApiStylesheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-queries': {
      id: '/api/media-queries'
      path: '/api/media-queries'
      fullPath: '/api/media-queries'
      preLoaderRoute: typeof ApiMediaQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/define-system': {
      id: '/api/define-system'
      path: '/api/define-system'
      fullPath: '/api/define-system'
      preLoaderRoute: typeof ApiDefineSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conditions': {
      id: '/api/conditions'
      path: '/api/conditions'
      fullPath: '/api/conditions'
      preLoaderRoute: typeof ApiConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UiRouteRouteChildren {
  UiComponentRoute: typeof UiComponentRoute
  UiIndexRoute: typeof UiIndexRoute
}

const UiRouteRouteChildren: UiRouteRouteChildren = {
  UiComponentRoute: UiComponentRoute,
  UiIndexRoute: UiIndexRoute,
}

const UiRouteRouteWithChildren =
  UiRouteRoute._addFileChildren(UiRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UiRouteRoute: UiRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ConceptsRoute: ConceptsRoute,
  ExamplesRoute: ExamplesRoute,
  ExploreRoute: ExploreRoute,
  GettingStartedRoute: GettingStartedRoute,
  LabRoute: LabRoute,
  PlaygroundRoute: PlaygroundRoute,
  ThemesRoute: ThemesRoute,
  ApiConditionsRoute: ApiConditionsRoute,
  ApiDefineSystemRoute: ApiDefineSystemRoute,
  ApiMediaQueriesRoute: ApiMediaQueriesRoute,
  ApiStylesheetRoute: ApiStylesheetRoute,
  ApiUseStylesRoute: ApiUseStylesRoute,
  ApiVariantsRoute: ApiVariantsRoute,
  GuidesInteractiveRoute: GuidesInteractiveRoute,
  GuidesOverridesRoute: GuidesOverridesRoute,
  GuidesReactNativeRoute: GuidesReactNativeRoute,
  GuidesReactWebRoute: GuidesReactWebRoute,
  GuidesSsrRoute: GuidesSsrRoute,
  GuidesThemingRoute: GuidesThemingRoute,
  LearnTopicRoute: LearnTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
