import type { Variants } from '@toned/core'
import { stylesheet } from '../system.ts'

/**
 * The page around the demo. It belongs to the documentation site, so it is
 * written against the site's system and keeps the site's look in every theme.
 */
export const themesPageStyles = stylesheet({
  Main: {
    flexLayout: 'column',
    gap: 10,
    measure: 'site',
    marginX: 'auto',
    paddingX: 4,
    paddingTop: 10,
    paddingBottom: 16,
    '@media md': { paddingX: 8, paddingTop: 14 },
  },
  Intro: { flexLayout: 'column', gap: 4, measure: 'article' },
  Lead: { textStyle: 'lead', text: 'muted', wrap: 'pretty' },
  Demo: { flexLayout: 'column', gap: 4 },
  Switcher: { display: 'flex', flexWrap: 'wrap', gap: 2 },
  Option: {
    $kind: 'pressable',
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    flexGrow: '1',
    minWidth: '148px',
    paddingX: 3,
    paddingY: 2,
    radius: 'lg',
    textStyle: 'ui',
    weight: 'semibold',
    text: 'default',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    cursor: 'pointer',
    motion: 'colors',
    ':hover': { borderTone: 'accent' },
  },
  Note: { textStyle: 'caption', text: 'muted', minHeight: '20px' },
  Frame: {
    radius: 'xl',
    overflow: 'hidden',
    border: 'all',
    borderTone: 'default',
  },
  Section: { flexLayout: 'column', gap: 4, anchor: 'below-header' },
  Heading: { textStyle: 'heading', weight: 'bold', text: 'default' },
  Copy: { measure: 'article', textStyle: 'prose', text: 'body' },
  Layers: {
    columns: 'single',
    gap: 5,
    alignItems: 'flex-start',
    '@media lg': { columns: 'even-halves' },
  },
  Layer: { flexLayout: 'column', gap: 3, minWidth: 0 },
  LayerTitle: { textStyle: 'subheading', weight: 'bold', text: 'default' },
  LayerNote: { textStyle: 'body-small', text: 'muted' },
  TableScroll: {
    overflowX: 'auto',
    overflowY: 'auto',
    maxHeight: '420px',
    radius: 'lg',
    border: 'all',
    borderTone: 'default',
    fill: 'surface',
  },
  Table: { width: '100%', textStyle: 'caption' },
  HeadCell: {
    paddingX: 3,
    paddingY: 2,
    textAlign: 'left',
    weight: 'semibold',
    text: 'muted',
    fill: 'sunken',
    border: 'bottom',
    borderTone: 'default',
    pin: 'top',
  },
  Cell: {
    paddingX: 3,
    paddingY: 1.5,
    border: 'bottom',
    borderTone: 'subtle',
    textStyle: 'code-inline',
    text: 'code',
    wrap: 'anywhere',
  },
  Field: {
    paddingX: 3,
    paddingY: 1.5,
    border: 'bottom',
    borderTone: 'subtle',
    textStyle: 'code-inline',
    textAlign: 'left',
    weight: 'semibold',
    text: 'default',
    wrap: 'nowrap',
  },
}).variants(($: Variants<{ selected: boolean }>) => ({
  [$.selected(true)]: {
    Option: {
      text: 'accent-strong',
      fill: 'accent-soft',
      borderTone: 'accent',
    },
  },
}))
