import type { Variants } from '@toned/core'
import { stylesheet } from './system.ts'

export const homeStyles = stylesheet({
  Page: {
    font: 'sans',
    textStyle: 'body',
    text: 'default',
    fill: 'page',
  },
  Container: {
    width: '100%',
    measure: 'home',
    marginX: 'auto',
    paddingX: 5,
    '@media md': { paddingX: 10 },
  },
  Hero: {
    flexLayout: 'column',
    alignItems: 'center',
    gap: 7,
    paddingTop: 14,
    paddingBottom: 12,
    textAlign: 'center',
    '@media md': { paddingTop: 20, paddingBottom: 16 },
  },
  Note: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    textStyle: 'caption',
    text: 'muted',
  },
  Title: {
    measure: 'headline',
    textStyle: 'display',
    weight: 'semibold',
    text: 'accent',
    wrap: 'balance',
  },
  Lead: {
    measure: 'lead',
    textStyle: 'intro',
    text: 'muted',
    '@media md': { textStyle: 'lead-large' },
  },
  Actions: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 3,
  },
  Primary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingX: 6,
    paddingY: 3,
    radius: 'md',
    textStyle: 'ui',
    weight: 'semibold',
    text: 'on-accent',
    fill: 'accent',
    ':hover': { opacity: 0.88 },
  },
  Secondary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingX: 6,
    paddingY: 3,
    radius: 'md',
    textStyle: 'ui',
    weight: 'semibold',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    ':hover': { fill: 'accent-soft' },
  },
  Studio: {
    overflow: 'hidden',
    radius: '4xl',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    elevation: 'floating',
  },
  StudioBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 3,
    paddingX: 6,
    paddingY: 4,
    textStyle: 'caption',
    border: 'bottom',
    borderTone: 'subtle',
  },
  Muted: { textStyle: 'caption', text: 'muted' },
  StudioGrid: {
    display: 'grid',
    gap: 6,
    padding: 5,
    '@media md': { columns: 'preview-controls', gap: 10, padding: 7 },
  },
  Preview: {
    display: 'flex',
    alignItems: 'center',
    minWidth: 0,
    minHeight: '360px',
  },
  Controls: {
    flexLayout: 'column',
    justifyContent: 'center',
    gap: 5,
    minWidth: 0,
  },
  Field: { flexLayout: 'column', gap: 2, minWidth: 0, border: 'none' },
  Label: { textStyle: 'caption', weight: 'semibold' },
  Choices: { display: 'flex', flexWrap: 'wrap', gap: 2 },
  Choice: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingX: 3,
    paddingY: 2,
    radius: 'md',
    textStyle: 'caption',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
  },
  StudioFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 2,
    justifyContent: 'space-between',
    paddingX: 6,
    paddingY: 4,
    textStyle: 'label',
    text: 'muted',
    fill: 'sunken',
    border: 'top',
    borderTone: 'subtle',
  },
  Section: {
    flexLayout: 'column',
    gap: 12,
    paddingY: 16,
    '@media md': { paddingY: 24 },
  },
  SectionIntro: {
    flexLayout: 'column',
    gap: 4,
    width: '100%',
    minWidth: 0,
    measure: 'intro',
  },
  Heading: {
    textStyle: 'headline',
    weight: 'semibold',
    wrap: 'balance',
  },
  Body: { measure: 'copy', textStyle: 'body-large', text: 'muted' },
  Features: {
    display: 'grid',
    gap: 10,
    '@media md': { columns: 'thirds', gap: 12 },
  },
  // Four cards: two rows of two rather than three and an orphan.
  FeaturePairs: {
    display: 'grid',
    gap: 10,
    '@media md': { columns: 'even-halves', gap: 12 },
  },
  Feature: { flexLayout: 'column', gap: 4, minWidth: 0 },
  FeatureIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 11,
    height: 11,
    radius: 'xl',
    textStyle: 'glyph',
    weight: 'semibold',
    text: 'accent',
    fill: 'accent-soft',
  },
  FeatureHeading: { textStyle: 'feature', weight: 'semibold' },
  FeatureBody: { textStyle: 'body-small', text: 'muted' },
  TextLink: {
    textStyle: 'ui',
    weight: 'semibold',
    text: 'accent',
    ':hover': { textDecoration: 'underline' },
  },
  SourceSection: {
    paddingY: 16,
    fill: 'accent-soft',
    '@media md': { paddingY: 20 },
  },
  SourceGrid: {
    columns: 'single',
    gap: 10,
    alignItems: 'flex-start',
    '@media md': { columns: 'steps-source', gap: 16 },
  },
  SourceScroll: { overflow: 'auto', maxHeight: '390px' },
  Source: {
    minWidth: 0,
    radius: 'xl',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
  },
  Steps: { flexLayout: 'column', gap: 6 },
  Step: { display: 'flex', gap: 4, alignItems: 'flex-start' },
  StepNumber: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: '0',
    width: 7,
    height: 7,
    radius: 'full',
    textStyle: 'label',
    text: 'accent',
    border: 'all',
    borderTone: 'accent-soft',
  },
  Banner: {
    flexLayout: 'column',
    gap: 8,
    padding: 8,
    radius: '3xl',
    text: 'on-accent',
    fill: 'accent',
    '@media md': {
      padding: 14,
      flexLayout: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
  },
  BannerTitle: { textStyle: 'banner', weight: 'semibold' },
  BannerText: { textStyle: 'body', text: 'on-accent-muted' },
  BannerLink: {
    paddingX: 5,
    paddingY: 3,
    radius: 'md',
    textStyle: 'ui',
    weight: 'semibold',
    wrap: 'nowrap',
    text: 'accent',
    fill: 'surface',
  },
})

export const choiceStyles = stylesheet({
  Button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingX: 3,
    paddingY: 2,
    minHeight: 11,
    radius: 'md',
    textStyle: 'caption',
    text: 'default',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
  },
}).variants(($: Variants<{ selected: boolean }>) => ({
  [$.selected(true)]: {
    Button: {
      text: 'accent-strong',
      fill: 'accent-soft',
      borderTone: 'accent',
    },
  },
}))
