import type { Variants } from '@toned/core'

import { stylesheet } from './system.ts'

export const homeStyles = stylesheet({
  Page: {
    font: 'sans',
    textStyle: 'body',
    text: 'default',
    fill: 'page',
  },
  Container: {
    width: '100%',
    measure: 'home',
    marginX: 'auto',
    paddingX: 5,
    '@media md': { paddingX: 10 },
  },

  // ── Hero ──────────────────────────────────────────────────────────────
  Hero: {
    flexLayout: 'column',
    alignItems: 'center',
    gap: 7,
    paddingTop: 12,
    paddingBottom: 8,
    textAlign: 'center',
    '@media md': { gap: 7, paddingTop: 18, paddingBottom: 10 },
  },
  Title: {
    measure: 'home',
    textStyle: 'display',
    weight: 'semibold',
    text: 'default',
    wrap: 'balance',
  },
  Lead: {
    measure: 'copy',
    textStyle: 'intro',
    text: 'muted',
    wrap: 'pretty',
    '@media md': { textStyle: 'lead-large' },
  },
  Actions: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 3,
  },
  Primary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingX: 6,
    paddingY: 3,
    radius: 'md',
    textStyle: 'ui',
    weight: 'semibold',
    text: 'on-accent',
    fill: 'accent',
    motion: 'colors',
    ':hover': { fill: 'accent-strong' },
  },
  Secondary: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingX: 6,
    paddingY: 3,
    radius: 'md',
    textStyle: 'ui',
    weight: 'semibold',
    text: 'default',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    motion: 'colors',
    ':hover': { fill: 'accent-soft', borderTone: 'accent-soft' },
  },

  // ── The line of supported targets ─────────────────────────────────────
  Support: {
    flexLayout: 'column',
    alignItems: 'center',
    gap: 4,
    paddingBottom: 6,
  },
  SupportLabel: { textStyle: 'overline', weight: 'semibold', text: 'faint' },
  Platforms: {
    columns: 'even-halves',
    gap: 3,
    width: '100%',
    measure: 'article',
    '@media md': { columns: 'quarters', gap: 4 },
  },
  Platform: {
    flexLayout: 'column',
    alignItems: 'center',
    gap: 1,
    height: '100%',
    paddingX: 3,
    paddingY: 5,
    radius: '2xl',
    textAlign: 'center',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    motion: 'lift',
    ':hover': { borderTone: 'accent', elevation: 'hover' },
  },
  PlatformIcon: { display: 'flex', text: 'accent', paddingBottom: 2 },
  PlatformName: {
    textStyle: 'subheading',
    weight: 'semibold',
    text: 'default',
  },
  PlatformNote: { textStyle: 'caption', text: 'muted', wrap: 'balance' },
  // The qualities the system is built around, as a compact grid.
  Pillars: {
    columns: 'single',
    gap: 6,
    paddingY: 10,
    '@media sm40': { columns: 'even-halves' },
    '@media lg': { columns: 'thirds', gap: 8, paddingY: 12 },
  },
  Pillar: {
    flexLayout: 'column',
    gap: 1,
    paddingLeft: 4,
    border: 'marker-left',
    borderTone: 'accent',
  },
  PillarTitle: { textStyle: 'subheading', weight: 'semibold', text: 'default' },
  PillarBody: { textStyle: 'body-small', text: 'muted', wrap: 'pretty' },
  Links: { display: 'flex', flexWrap: 'wrap', columnGap: 6, rowGap: 2 },
  Chip: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    paddingX: 4,
    paddingY: 2,
    radius: 'full',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    wrap: 'nowrap',
  },
  ChipKind: { textStyle: 'overline', weight: 'semibold', text: 'accent' },
  ChipName: { textStyle: 'ui', weight: 'semibold', text: 'default' },
  ChipNote: { textStyle: 'caption', text: 'muted' },

  // ── Sections ──────────────────────────────────────────────────────────
  Section: {
    flexLayout: 'column',
    gap: 10,
    paddingY: 12,
    anchor: 'below-header',
    '@media md': { gap: 12, paddingY: 18 },
  },
  // A full-width tinted band; its content sits in a Container.
  Band: {
    fill: 'accent-soft',
    border: 'top',
    borderTone: 'accent-soft',
  },
  SectionIntro: {
    flexLayout: 'column',
    gap: 4,
    width: '100%',
    minWidth: 0,
    measure: 'article',
  },
  Eyebrow: { textStyle: 'eyebrow', weight: 'semibold', text: 'accent' },
  Heading: {
    textStyle: 'headline',
    weight: 'semibold',
    text: 'default',
    wrap: 'balance',
  },
  Body: { textStyle: 'body-large', text: 'muted', wrap: 'pretty' },
  TextLink: {
    textStyle: 'ui',
    weight: 'semibold',
    text: 'accent',
    ':hover': { textDecoration: 'underline' },
  },

  // ── Themes ────────────────────────────────────────────────────────────
  ThemeDemo: { flexLayout: 'column', gap: 4, minWidth: 0 },
  // On a phone the interface is taller than the screen, so it scrolls in
  // place. From `md` up the cap is a percentage of an auto height, which
  // computes to no cap.
  ThemeFrame: {
    radius: '3xl',
    overflowX: 'hidden',
    overflowY: 'auto',
    maxHeight: '560px',
    border: 'all',
    borderTone: 'default',
    elevation: 'floating',
    '@media md': { maxHeight: '100%' },
  },
  Facts: {
    columns: 'single',
    gap: 4,
    '@media md': { columns: 'thirds', gap: 6 },
  },
  Fact: {
    flexLayout: 'column',
    gap: 1,
    paddingLeft: 4,
    border: 'marker-left',
    borderTone: 'accent-soft',
  },
  FactTitle: { textStyle: 'ui', weight: 'semibold', text: 'default' },
  FactBody: { textStyle: 'body-small', text: 'muted' },

  // ── How it works ──────────────────────────────────────────────────────
  Story: {
    columns: 'single',
    gap: 8,
    alignItems: 'flex-start',
    '@media lg': { columns: 'steps-source', gap: 12 },
  },
  Result: {
    flexLayout: 'column',
    gap: 5,
    minWidth: 0,
    padding: 5,
    radius: '3xl',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    elevation: 'panel',
    '@media lg': { padding: 6 },
  },
  // Stays in view on a wide screen while the steps scroll past; the
  // padding keeps the panel clear of the header it is pinned under.
  ResultPin: {
    minWidth: 0,
    '@media lg': { pin: 'below-header', paddingTop: 6 },
  },
  ResultLabel: { textStyle: 'overline', weight: 'semibold', text: 'faint' },
  Stage: {
    display: 'flex',
    alignItems: 'center',
    minHeight: '168px',
    padding: 5,
    radius: 'xl',
    fill: 'sunken',
    texture: 'dots',
  },
  StageInner: { width: '100%', minWidth: 0 },
  Controls: { flexLayout: 'column', gap: 4 },
  Field: { flexLayout: 'column', gap: 2, minWidth: 0 },
  FieldLabel: { textStyle: 'caption', weight: 'semibold', text: 'default' },
  Choices: { display: 'flex', flexWrap: 'wrap', gap: 2 },
  Usage: {
    paddingX: 3,
    paddingY: 2,
    radius: 'md',
    textStyle: 'code',
    text: 'code',
    fill: 'code',
    wrap: 'pre-wrap-anywhere',
  },
  Steps: {
    flexLayout: 'column',
    gap: 10,
    minWidth: 0,
    '@media lg': { paddingTop: 6 },
  },
  Step: { flexLayout: 'column', gap: 3, minWidth: 0 },
  StepHead: { display: 'flex', alignItems: 'center', gap: 3 },
  StepNumber: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: '0',
    width: 8,
    height: 8,
    radius: 'full',
    textStyle: 'ui',
    weight: 'semibold',
    text: 'on-accent',
    fill: 'accent',
  },
  StepTitle: { textStyle: 'heading', weight: 'semibold', text: 'default' },
  StepBody: { textStyle: 'body', text: 'body', wrap: 'pretty' },
  // What the compiler prints for a value the token does not list.
  Diagnostic: {
    flexLayout: 'column',
    minWidth: 0,
    radius: 'xl',
    overflow: 'hidden',
    fill: 'surface',
    border: 'all',
    borderTone: 'danger',
  },
  DiagnosticCode: {
    paddingX: 4,
    paddingY: 3,
    textStyle: 'code',
    text: 'code',
    fill: 'code',
    overflowX: 'auto',
  },
  DiagnosticMark: { text: 'danger', weight: 'semibold' },
  DiagnosticMessage: {
    paddingX: 4,
    paddingY: 3,
    textStyle: 'caption',
    font: 'mono',
    text: 'danger-strong',
    fill: 'danger-soft',
    border: 'top',
    borderTone: 'danger',
    wrap: 'anywhere',
  },
  Outputs: {
    columns: 'single',
    gap: 4,
    '@media md': { columns: 'even-halves' },
  },
  Output: { flexLayout: 'column', gap: 2, minWidth: 0 },

  // ── Capabilities ──────────────────────────────────────────────────────
  Cards: {
    columns: 'single',
    gap: 4,
    '@media sm40': { columns: 'even-halves' },
    '@media lg': { columns: 'thirds', gap: 5 },
  },
  Card: {
    flexLayout: 'column',
    gap: 2,
    minWidth: 0,
    padding: 6,
    radius: '2xl',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
  },
  CardTitle: { textStyle: 'subheading', weight: 'semibold', text: 'default' },
  CardBody: { textStyle: 'body-small', text: 'muted', flexGrow: '1' },

  // ── Where next ────────────────────────────────────────────────────────
  Banner: {
    flexLayout: 'column',
    gap: 6,
    padding: 8,
    radius: '3xl',
    text: 'on-accent',
    fill: 'accent',
    '@media md': {
      padding: 12,
      flexLayout: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
  },
  BannerIntro: { flexLayout: 'column', gap: 2, measure: 'copy' },
  BannerTitle: { textStyle: 'banner', weight: 'semibold' },
  BannerText: { textStyle: 'body', text: 'on-accent-muted' },
  BannerLink: {
    paddingX: 6,
    paddingY: 3,
    radius: 'md',
    textStyle: 'ui',
    weight: 'semibold',
    wrap: 'nowrap',
    text: 'accent',
    fill: 'surface',
    ':hover': { fill: 'accent-soft' },
  },
  Tiles: {
    columns: 'single',
    gap: 4,
    '@media sm40': { columns: 'even-halves' },
    '@media lg': { columns: 'cards' },
  },
  Tile: {
    flexLayout: 'column',
    gap: 2,
    minWidth: 0,
    padding: 6,
    radius: '2xl',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    motion: 'lift',
    ':hover': { borderTone: 'accent', elevation: 'hover' },
  },
  TileTitle: { textStyle: 'subheading', weight: 'semibold', text: 'accent' },
  TileBody: { textStyle: 'body-small', text: 'muted' },
})

export const choiceStyles = stylesheet({
  Button: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingX: 3,
    paddingY: 2,
    minHeight: 11,
    radius: 'md',
    textStyle: 'caption',
    text: 'default',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    cursor: 'pointer',
  },
}).variants(($: Variants<{ selected: boolean }>) => ({
  [$.selected(true)]: {
    Button: {
      text: 'accent-strong',
      fill: 'accent-soft',
      borderTone: 'accent',
    },
  },
}))

/** The mock editor in the tooling section. */
export const tourStyles = stylesheet({
  Tour: { flexLayout: 'column', gap: 4, minWidth: 0 },
  Tabs: { display: 'flex', flexWrap: 'wrap', gap: 2 },
  Window: {
    flexLayout: 'column',
    minWidth: 0,
    radius: '3xl',
    overflow: 'hidden',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    elevation: 'panel',
  },
  TitleBar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    columnGap: 4,
    rowGap: 1,
    paddingX: 5,
    paddingY: 3,
    fill: 'code-chrome',
    border: 'bottom',
    borderTone: 'default',
  },
  FileName: { textStyle: 'code', weight: 'semibold', text: 'default' },
  Summary: { textStyle: 'caption', text: 'muted' },
  // Tall enough for the longest case, so switching does not move the page.
  Code: {
    minHeight: '292px',
    paddingX: 5,
    paddingY: 5,
    textStyle: 'code',
    text: 'code',
    fill: 'code',
    overflowX: 'auto',
    '@media md': { minHeight: '236px' },
  },
  Line: { wrap: 'pre' },
  Mark: {
    radius: 'xs',
    fill: 'accent-soft',
    // No token: an editor's squiggle has no counterpart off the web.
    '@platform web': {
      $style: { boxShadow: '0 0 0 2px #edf1ff' },
    },
  },
  Popup: {
    flexLayout: 'column',
    gap: 1,
    marginY: 2,
    marginLeft: 4,
    padding: 3,
    measure: 'copy',
    radius: 'lg',
    font: 'sans',
    fill: 'surface',
    border: 'all',
    borderTone: 'strong',
    elevation: 'raised',
    wrap: 'normal',
    '@media md': { marginLeft: 10 },
  },
  Rows: { flexLayout: 'column', gap: 1 },
  Row: { display: 'flex', flexWrap: 'wrap', columnGap: 4, rowGap: 0 },
  RowLabel: {
    textStyle: 'code',
    weight: 'semibold',
    text: 'default',
    minWidth: '128px',
  },
  RowValue: { textStyle: 'code', text: 'muted' },
  ProblemSource: { textStyle: 'caption', weight: 'semibold', text: 'danger' },
  ProblemText: {
    textStyle: 'caption',
    font: 'mono',
    text: 'danger-strong',
    wrap: 'anywhere',
  },
}).variants(
  ($: Variants<{ tone: 'info' | 'error' }>) => ({
    [$.tone('error')]: {
      Mark: {
        fill: 'danger-soft',
        '@platform web': {
          $style: {
            boxShadow: '0 0 0 2px #fdecea',
            textDecoration: 'underline wavy #b3261e',
            textUnderlineOffset: '4px',
          },
        },
      },
      Popup: { borderTone: 'danger', fill: 'danger-soft' },
    },
  }),
  { defaults: { tone: 'info' } },
)
