import { stylesheet } from '@toned/systems/base'

export const libraryStyles = stylesheet({
  page: {
    fontFamily: '"Avenir Next", Avenir, "Segoe UI", sans-serif',
    style: { color: '#17234b', backgroundColor: '#fbfcff' },
    flexLayout: 'column',
    gap: 8,
    minHeight: '100vh',
    paddingX: 4,
    paddingY: 6,
    '@md': { paddingX: 10 },
  },
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
  },
  nav: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
    fontSize: '14px',
  },
  shell: { flexLayout: 'column', gap: 8, '@md': { flexLayout: 'row' } },
  main: { flexGrow: '1', minWidth: '0' },
  stack: { flexLayout: 'column', gap: 5, minWidth: '0' },
  row: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 3 },
  spread: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 3,
  },
  eyebrow: {
    textColor: 'action',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  title: {
    fontSize: '36px',
    lineHeight: 1.1,
    fontWeight: 650,
    letterSpacing: '-0.045em',
    '@md': { fontSize: '56px' },
  },
  intro: {
    textColor: 'muted',
    fontSize: '17px',
    lineHeight: 1.7,
    maxWidth: '680px',
  },
  workbench: {
    display: 'grid',
    gap: 5,
    minWidth: '0',
    alignItems: 'flex-start',
    style: { gridTemplateColumns: 'minmax(0, 1fr)' },
    '@md': {
      style: { gridTemplateColumns: 'minmax(0, 0.9fr) minmax(0, 1.1fr)' },
    },
  },
  grid: {
    display: 'grid',
    gap: 5,
    style: { gridTemplateColumns: 'minmax(0, 1fr)' },
    '@md': { style: { gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' } },
  },
  panel: {
    flexLayout: 'column',
    gap: 4,
    padding: 5,
    bgColor: 'elevated',
    style: { borderStyle: 'solid' },
    borderColor: 'default',
    borderWidth: 'thin',
    borderRadius: 'xlarge',
    minWidth: '0',
  },
  metric: {
    fontSize: '40px',
    fontWeight: 600,
    letterSpacing: '-0.04em',
    lineHeight: 1.1,
  },
  muted: { textColor: 'muted', fontSize: '13px', lineHeight: 1.6 },
  divider: { paddingY: 3, style: { borderBottom: '1px solid var(--border)' } },
  editor: {
    width: '100%',
    minHeight: '220px',
    padding: 4,
    borderRadius: 'large',
    bgColor: 'muted',
    textColor: 'default',
    borderWidth: 'thin',
    borderColor: 'default',
    fontFamily: 'monospace',
    fontSize: '13px',
    lineHeight: 1.7,
    style: { resize: 'vertical', tabSize: 2 },
  },
  inspector: { maxWidth: '100%', overflowX: 'auto', $style: { minWidth: 0 } },
  source: { maxHeight: '520px', overflow: 'auto', minWidth: '0' },
  label: { fontSize: '14px', fontWeight: 600 },
  input: {
    width: '100%',
    padding: 3,
    style: { borderStyle: 'solid' },
    borderColor: 'default',
    borderWidth: 'thin',
    borderRadius: 'large',
    bgColor: 'default',
    textColor: 'default',
    fontSize: '14px',
  },
  sidebar: {
    flexLayout: 'column',
    gap: 3,
    '@md': {
      width: '190px',
      flexShrink: '0',
      alignSelf: 'flex-start',
      position: 'sticky',
      top: '24px',
      maxHeight: 'calc(100vh - 48px)',
      overflowY: 'auto',
    },
  },
  links: {
    maxHeight: '160px',
    overflowY: 'auto',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1,
    '@md': {
      flexLayout: 'column',
      maxHeight: 'calc(100vh - 180px)',
      flexWrap: 'nowrap',
    },
  },
  link: {
    paddingX: 3,
    paddingY: 2,
    borderRadius: 'medium',
    textColor: 'muted',
    fontSize: '13px',
    textDecoration: 'none',
    ':hover': { bgColor: 'subtle' },
  },
  activeLink: {
    bgColor: 'action_secondary',
    textColor: 'on_action_secondary',
    fontWeight: 600,
  },
})
