import { stylesheet } from './system.ts'

/**
 * Chrome for the component gallery and the lab's demos. These surfaces sit
 * beside the gallery's own components, so their colours stay on the base
 * system's roles, which the gallery theme supplies.
 */
export const libraryStyles = stylesheet({
  page: {
    font: 'sans',
    text: 'default',
    fill: 'page',
    flexLayout: 'column',
    gap: 8,
    minHeight: '100vh',
    paddingX: 4,
    paddingY: 6,
    '@media md': { paddingX: 10 },
  },
  header: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
  },
  nav: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
    fontSize: '14px',
  },
  shell: { flexLayout: 'column', gap: 8, '@media md': { flexLayout: 'row' } },
  main: { flexGrow: '1', minWidth: 0 },
  stack: { flexLayout: 'column', gap: 5, minWidth: 0 },
  row: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 3 },
  spread: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 3,
  },
  eyebrow: {
    textColor: 'action',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  title: {
    fontSize: '36px',
    lineHeight: 1.1,
    fontWeight: 650,
    letterSpacing: '-0.045em',
    '@media md': { fontSize: '56px' },
  },
  intro: {
    textColor: 'muted',
    fontSize: '17px',
    lineHeight: 1.7,
    maxWidth: '680px',
  },
  workbench: {
    columns: 'single',
    gap: 5,
    minWidth: 0,
    alignItems: 'flex-start',
    '@media md': { columns: 'source-preview' },
  },
  grid: {
    columns: 'single',
    gap: 5,
    '@media md': { columns: 'even-halves' },
  },
  panel: {
    flexLayout: 'column',
    gap: 4,
    padding: 5,
    bgColor: 'elevated',
    border: 'all',
    borderColor: 'default',
    borderRadius: 'xlarge',
    minWidth: 0,
  },
  metric: {
    fontSize: '40px',
    fontWeight: 600,
    letterSpacing: '-0.04em',
    lineHeight: 1.1,
  },
  muted: { textColor: 'muted', fontSize: '13px', lineHeight: 1.6 },
  divider: { paddingY: 3, border: 'bottom', borderColor: 'default' },
  editor: {
    width: '100%',
    minHeight: '220px',
    padding: 4,
    borderRadius: 'large',
    bgColor: 'muted',
    textColor: 'default',
    borderWidth: 'thin',
    borderColor: 'default',
    fontFamily: 'monospace',
    fontSize: '13px',
    lineHeight: 1.7,
    // No token: native <textarea> behaviour.
    '@platform web': { $style: { resize: 'vertical', tabSize: 2 } },
  },
  inspector: { maxWidth: '100%', overflowX: 'auto', minWidth: 0 },
  source: { maxHeight: '520px', overflow: 'auto', minWidth: 0 },
  label: { fontSize: '14px', fontWeight: 600 },
  input: {
    width: '100%',
    padding: 3,
    border: 'all',
    borderColor: 'default',
    borderRadius: 'large',
    bgColor: 'default',
    textColor: 'default',
    fontSize: '14px',
  },
  sidebar: {
    flexLayout: 'column',
    gap: 3,
    '@media md': {
      width: '190px',
      flexShrink: '0',
      alignSelf: 'flex-start',
      position: 'sticky',
      top: 6,
      maxHeight: 'calc(100vh - 48px)',
      overflowY: 'auto',
    },
  },
  links: {
    maxHeight: '160px',
    overflowY: 'auto',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1,
    '@media md': {
      flexLayout: 'column',
      maxHeight: 'calc(100vh - 180px)',
      flexWrap: 'nowrap',
    },
  },
  link: {
    paddingX: 3,
    paddingY: 2,
    borderRadius: 'medium',
    textColor: 'muted',
    fontSize: '13px',
    textDecoration: 'none',
    ':hover': { bgColor: 'subtle' },
  },
  activeLink: {
    bgColor: 'action_secondary',
    textColor: 'on_action_secondary',
    fontWeight: 600,
  },
})
