import type { Variants } from '@toned/core'
import { editorMetrics } from './brand.ts'
import { stylesheet } from './system.ts'

export { editorMetrics }

// The static code must sit exactly where CodeMirror will draw it, so its
// padding comes from the shared metrics rather than the spacing scale.
const codePadding = (x: number) => `${editorMetrics.paddingY}px ${x}px`

// No token: the chevron is drawn into the native <select> itself.
const chevron = (inset: number) =>
  ({
    appearance: 'none',
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6' fill='none'%3E%3Cpath d='M1 1l4 4 4-4' stroke='%235d6784' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: `right ${inset}px center`,
  }) as const

/** Toolbar buttons and selects share one control. */
const control = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: 2,
  height: 8,
  paddingX: 3,
  radius: 'md',
  cursor: 'pointer',
  font: 'sans',
  textStyle: 'caption',
  weight: 'semibold',
  wrap: 'nowrap',
  text: 'default',
  fill: 'surface',
  border: 'all',
  borderTone: 'default',
  ':hover': { fill: 'tint', borderTone: 'strong' },
} as const

const frame = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  marginX: 'auto',
  width: '100%',
  minHeight: '100%',
  motion: 'resize',
} as const

const panel = {
  flexLayout: 'column',
  minWidth: 0,
  minHeight: 0,
  overflow: 'hidden',
  radius: 'xl',
  fill: 'surface',
  border: 'all',
  borderTone: 'default',
  elevation: 'panel',
} as const

const dot = {
  flexShrink: '0',
  width: 2,
  height: 2,
  radius: 'full',
  fill: 'neutral',
} as const

export const playgroundEditorStyles = stylesheet({
  Page: {
    flexLayout: 'column',
    minHeight: '100vh',
    font: 'sans',
    textStyle: 'ui',
    text: 'default',
    fill: 'page',
    '@media md': { height: '100dvh', overflow: 'hidden' },
  },
  Main: { flexLayout: 'column', flexGrow: '1', minHeight: 0 },
  Toolbar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 3,
    paddingX: 3,
    paddingTop: 3,
    '@media md': { flexWrap: 'nowrap', paddingX: 4 },
  },
  ToolbarGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    minWidth: 0,
    '@media md': { gap: 3 },
  },
  Title: {
    $kind: 'text',
    textStyle: 'body',
    weight: 'heavy',
    letterSpacing: '-0.02em',
    wrap: 'nowrap',
    text: 'default',
  },
  Summary: {
    $kind: 'text',
    display: 'none',
    textStyle: 'caption',
    wrap: 'truncate',
    text: 'muted',
    '@media lg': { display: 'block' },
  },
  SelectLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    textStyle: 'caption',
    weight: 'semibold',
    text: 'muted',
  },
  Select: {
    ...control,
    paddingRight: 8,
    maxWidth: '100%',
    '@platform web': { $style: chevron(10) },
  },
  Button: control,
  PrimaryButton: {
    ...control,
    text: 'on-accent',
    fill: 'accent',
    borderTone: 'accent',
    ':hover': { fill: 'accent-strong' },
  },
  Pill: {
    $kind: 'text',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    height: 7,
    paddingX: 3,
    radius: 'full',
    textStyle: 'label',
    weight: 'semibold',
    wrap: 'nowrap',
    numeric: 'tabular',
    text: 'muted',
    fill: 'tint',
    border: 'all',
    borderTone: 'subtle',
  },
  Dot: dot,
  Workspace: {
    flexLayout: 'column',
    gap: 3,
    padding: 3,
    '@media md': {
      display: 'grid',
      gap: 0,
      paddingX: 4,
      paddingBottom: 4,
      paddingTop: 3,
      flexGrow: '1',
      minHeight: 0,
    },
  },
  EditorPanel: {
    ...panel,
    height: '460px',
    '@media md': { height: 'auto' },
  },
  PreviewPanel: {
    ...panel,
    minHeight: '480px',
    '@media md': { minHeight: 0 },
  },
  TabBar: {
    display: 'flex',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    flexShrink: '0',
    gap: 2,
    bar: 'tabs',
    paddingX: 2,
    fill: 'surface',
    border: 'bottom',
    borderTone: 'subtle',
  },
  TabList: {
    display: 'flex',
    alignItems: 'stretch',
    gap: 1,
    minWidth: 0,
    overflowX: 'auto',
  },
  Tab: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    paddingX: 3,
    cursor: 'pointer',
    font: 'sans',
    textStyle: 'caption',
    weight: 'semibold',
    wrap: 'nowrap',
    text: 'muted',
    fill: 'none',
    border: 'marker-bottom',
    borderTone: 'none',
    // One-off: the marker overlaps the tab bar's own hairline.
    '@platform web': { $style: { marginBottom: -1 } },
    ':hover': { text: 'default' },
  },
  // A file tab reads as two lines: the layer the file is, then its name.
  FileLabel: { flexLayout: 'column', alignItems: 'flex-start' },
  FileLayer: {
    $kind: 'text',
    textStyle: 'badge',
    weight: 'heavy',
    text: 'faint',
  },
  FileName: { display: 'inline-flex', alignItems: 'center', gap: 2 },
  TabMeta: {
    display: 'none',
    '@media md': { display: 'flex' },
    alignItems: 'center',
    gap: 2,
    paddingRight: 2,
    textStyle: 'label',
    wrap: 'nowrap',
    text: 'faint',
  },
  WidthControl: {
    display: 'none',
    alignItems: 'center',
    gap: 2,
    paddingRight: 2,
    textStyle: 'label',
    wrap: 'nowrap',
    text: 'faint',
    '@media md': { display: 'flex' },
  },
  Editor: {
    position: 'relative',
    display: 'flex',
    flexGrow: '1',
    minHeight: 0,
    text: 'code',
    fill: 'code',
  },
  StaticCode: { display: 'flex', width: '100%', overflow: 'hidden' },
  Gutter: {
    flexShrink: '0',
    width: 12,
    textStyle: 'editor',
    textAlign: 'right',
    text: 'faint',
    border: 'right',
    borderTone: 'subtle',
    '@platform web': {
      $style: { padding: codePadding(10), userSelect: 'none' },
    },
  },
  Highlight: {
    textStyle: 'editor',
    text: 'code',
    '@platform web': {
      $style: { padding: codePadding(editorMetrics.paddingX) },
    },
  },
  EditorHost: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  ProblemsPanel: {
    flexLayout: 'column',
    flexShrink: '0',
    padding: 1,
    maxHeight: '148px',
    overflowY: 'auto',
    fill: 'surface',
    border: 'top',
    borderTone: 'subtle',
    // No token: resets the marker of the list element this part renders as.
    '@platform web': { $style: { listStyle: 'none' } },
  },
  ProblemRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 2,
    width: '100%',
    paddingX: 2,
    paddingY: 1,
    radius: 'sm',
    cursor: 'pointer',
    font: 'sans',
    textStyle: 'label',
    lineHeight: '18px',
    textAlign: 'left',
    text: 'body',
    fill: 'none',
    border: 'none',
    ':hover': { fill: 'tint' },
  },
  ProblemSource: {
    $kind: 'text',
    flexShrink: '0',
    minWidth: '38px',
    paddingX: 1,
    radius: 'xs',
    textStyle: 'badge',
    weight: 'heavy',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    textAlign: 'center',
    text: 'danger',
    fill: 'danger-soft',
  },
  ProblemLocation: {
    $kind: 'text',
    flexShrink: '0',
    font: 'mono',
    fontSize: '11.5px',
    wrap: 'nowrap',
    text: 'accent',
  },
  ProblemText: { $kind: 'text', minWidth: 0, wrap: 'pre-wrap-anywhere' },
  ProblemsButton: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: '0',
    gap: 2,
    height: 6,
    paddingX: 2,
    radius: 'sm',
    cursor: 'pointer',
    font: 'sans',
    textStyle: 'label',
    weight: 'semibold',
    wrap: 'nowrap',
    text: 'muted',
    fill: 'none',
    border: 'none',
    ':hover': { fill: 'tint' },
  },
  ProblemsDot: dot,
  TabBadge: {
    $kind: 'text',
    minWidth: 4,
    paddingX: 1,
    radius: 'full',
    textStyle: 'badge',
    weight: 'heavy',
    numeric: 'tabular',
    textAlign: 'center',
    text: 'on-accent',
    fill: 'danger',
  },
  SrOnly: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    overflow: 'hidden',
    wrap: 'nowrap',
    // No token: the standard visually-hidden clip.
    '@platform web': { $style: { clipPath: 'inset(50%)' } },
  },
  StatusGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    minWidth: 0,
    wrap: 'truncate',
  },
  Counts: { $kind: 'text', flexShrink: '0', numeric: 'tabular' },
  StatusBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexShrink: '0',
    gap: 3,
    bar: 'status',
    paddingX: 3,
    overflow: 'hidden',
    textStyle: 'label',
    wrap: 'nowrap',
    text: 'muted',
    fill: 'surface',
    border: 'top',
    borderTone: 'subtle',
  },
  Hint: { display: 'none', '@media md': { display: 'inline' } },
  Divider: {
    display: 'none',
    '@media md': {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      // No token: drag-handle behaviour for the pointer-driven splitter.
      '@platform web': {
        $style: { cursor: 'col-resize', touchAction: 'none' },
      },
    },
  },
  DividerHandle: { width: 1, height: 10, radius: 'full', fill: 'rule' },
  Controls: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    flexShrink: '0',
    gap: 3,
    paddingX: 4,
    paddingY: 3,
    fill: 'surface',
    border: 'bottom',
    borderTone: 'subtle',
  },
  ControlsLabel: {
    $kind: 'text',
    textStyle: 'overline',
    weight: 'heavy',
    text: 'faint',
  },
  Control: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    textStyle: 'caption',
    weight: 'semibold',
    text: 'body',
  },
  SmallSelect: {
    ...control,
    height: 7,
    paddingX: 2,
    paddingRight: 7,
    textStyle: 'label',
    '@platform web': { $style: chevron(8) },
  },
  Checkbox: { width: 4, height: 4 },
  Note: { $kind: 'text', textStyle: 'label', text: 'faint' },
  Stage: {
    position: 'relative',
    display: 'flex',
    flexGrow: '1',
    minHeight: 0,
    padding: 5,
    overflow: 'auto',
    fill: 'page',
    texture: 'dots',
  },
  Frame: frame,
  FramedBox: {
    ...frame,
    radius: 'xs',
    // No token: a dashed guide drawn outside the box, around the set width.
    '@platform web': {
      $style: {
        outlineWidth: 1,
        outlineStyle: 'dashed',
        outlineColor: '#dce2f4',
        outlineOffset: 8,
      },
    },
  },
  PreviewRoot: { width: '100%', display: 'flex', justifyContent: 'center' },
  Placeholder: {
    $kind: 'text',
    margin: 'auto',
    textStyle: 'caption',
    text: 'faint',
  },
  Problem: {
    flexLayout: 'column',
    flexShrink: '0',
    gap: 1,
    paddingX: 4,
    paddingY: 3,
    maxHeight: '40%',
    overflow: 'auto',
    text: 'danger',
    fill: 'danger-soft',
    border: 'top',
    borderTone: 'danger',
  },
  ProblemHead: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 2,
    textStyle: 'label',
    weight: 'heavy',
    letterSpacing: '0.02em',
  },
  ProblemLink: {
    cursor: 'pointer',
    font: 'mono',
    textStyle: 'label',
    weight: 'semibold',
    textDecoration: 'underline',
    text: 'danger',
    fill: 'none',
    border: 'none',
    // No token: underline placement for this one inline link.
    '@platform web': { $style: { textUnderlineOffset: 3 } },
  },
  ProblemMessage: {
    $kind: 'text',
    font: 'mono',
    textStyle: 'label',
    lineHeight: '18px',
    wrap: 'pre-wrap-anywhere',
    text: 'danger-strong',
  },
  ProblemNote: { $kind: 'text', textStyle: 'label', text: 'body' },
  Output: { flexGrow: '1', minHeight: 0, overflow: 'auto', fill: 'code' },
  OutputSection: {
    flexLayout: 'column',
    border: 'bottom',
    borderTone: 'subtle',
  },
  OutputHead: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: 2,
    paddingX: 4,
    paddingTop: 3,
    textStyle: 'label',
    weight: 'heavy',
    text: 'default',
  },
  OutputMeta: {
    $kind: 'text',
    textStyle: 'label',
    weight: 'medium',
    text: 'faint',
  },
  OutputCode: {
    paddingTop: 3,
    paddingX: 4,
    paddingBottom: 4,
    overflowX: 'auto',
    textStyle: 'output',
    text: 'code',
  },
  Empty: {
    $kind: 'text',
    paddingX: 4,
    paddingY: 4,
    textStyle: 'caption',
    text: 'muted',
  },
}).variants(
  (
    $: Variants<{
      active: boolean
      status: 'loading' | 'ok' | 'error'
      level: 'none' | 'clean' | 'error' | 'warning' | 'info'
    }>,
  ) => ({
    [$.level('clean')]: { ProblemsDot: { fill: 'success' } },
    [$.level('error')]: {
      ProblemsDot: { fill: 'danger' },
      ProblemsButton: { text: 'danger' },
      Counts: { text: 'danger' },
    },
    [$.level('warning')]: {
      ProblemsDot: { fill: 'warning' },
      ProblemsButton: { text: 'warning' },
      ProblemSource: { text: 'warning', fill: 'warning-soft' },
      TabBadge: { fill: 'warning' },
    },
    [$.level('info')]: {
      ProblemsDot: { fill: 'accent' },
      ProblemSource: { text: 'accent', fill: 'accent-soft' },
      TabBadge: { fill: 'accent' },
    },
    [$.active(true)]: {
      Tab: { text: 'default', borderTone: 'accent' },
      FileLayer: { text: 'accent' },
    },
    [$.status('ok')]: {
      Pill: { text: 'success', fill: 'success-soft', borderTone: 'success' },
      Dot: { fill: 'success' },
    },
    [$.status('error')]: {
      Pill: { text: 'danger', fill: 'danger-soft', borderTone: 'danger' },
      Dot: { fill: 'danger' },
    },
  }),
  { defaults: { active: false, status: 'loading', level: 'none' } },
)
