import type { Variants } from '@toned/core'
import { stylesheet } from './system.ts'

/**
 * The component gallery's detail page: header, preview stage, prop controls
 * and the source workbench. The components shown on the stage bring their own
 * stylesheets; this sheet styles only the page around them.
 */
export const playgroundStyles = stylesheet({
  // The gallery's theme switcher, above every gallery page.
  gallery: { flexLayout: 'column', gap: 8, minWidth: 0 },
  themeBar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 3,
    minWidth: 0,
    paddingBottom: 5,
    border: 'bottom',
    borderTone: 'subtle',
  },
  themeLabel: { textStyle: 'overline', weight: 'semibold', text: 'faint' },
  themeOptions: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 1.5,
    minWidth: 0,
  },
  themeOption: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    minHeight: '32px',
    paddingLeft: 1.5,
    paddingRight: 3,
    radius: 'full',
    textStyle: 'caption',
    weight: 'semibold',
    text: 'body',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    cursor: 'pointer',
    motion: 'colors',
    ':hover': { borderTone: 'accent' },
  },
  // Its colours come from gallery-themes.css, keyed on the option's theme.
  themeSwatch: {
    width: '20px',
    height: '20px',
    flexShrink: '0',
    radius: 'full',
    border: 'all',
    borderTone: 'default',
  },
  note: {
    measure: 'article',
    textStyle: 'body-small',
    lineHeight: 1.6,
    text: 'muted',
    wrap: 'pretty',
  },
  // A themed backdrop behind a demo; it has no box of its own in Modern.
  stage: { flexLayout: 'column', gap: 5, minWidth: 0 },

  container: { flexLayout: 'column', gap: 8, minWidth: 0 },
  header: { flexLayout: 'column', minWidth: 0 },
  title: { textStyle: 'title', weight: 'bold', text: 'default' },
  description: {
    marginTop: 3,
    measure: 'article',
    textStyle: 'lead',
    text: 'muted',
    wrap: 'pretty',
  },
  exportBadge: {
    marginTop: 4,
    font: 'mono',
    textStyle: 'label',
    lineHeight: 1.7,
    text: 'faint',
    wrap: 'anywhere',
  },

  // Preview and props on one side, source on the other, from the `xl` width.
  workbench: {
    columns: 'single',
    gap: 6,
    minWidth: 0,
    alignItems: 'flex-start',
    '@media xl': { columns: 'even-halves' },
  },
  column: { flexLayout: 'column', gap: 6, minWidth: 0 },
  preview: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    minHeight: '320px',
    paddingX: 4,
    paddingY: 10,
    radius: '2xl',
    fill: 'surface',
    texture: 'dots-wide',
    border: 'all',
    borderTone: 'default',
    '@media md': { paddingX: 8 },
  },
  previewError: {
    paddingX: 4,
    paddingY: 3,
    radius: 'md',
    font: 'mono',
    textStyle: 'caption',
    fill: 'danger-soft',
    text: 'danger-strong',
    border: 'all',
    borderTone: 'danger',
    wrap: 'anywhere',
  },
  compoundNotice: {
    flexLayout: 'column',
    alignItems: 'center',
    gap: 1,
    textStyle: 'caption',
    text: 'muted',
    textAlign: 'center',
  },

  // Prop controls.
  controls: {
    flexLayout: 'column',
    radius: '2xl',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    minWidth: 0,
    overflow: 'hidden',
  },
  // A heading for each documented component's group of props.
  controlsTitle: {
    paddingX: 5,
    paddingY: 2.5,
    font: 'mono',
    textStyle: 'label',
    weight: 'semibold',
    text: 'muted',
    fill: 'sunken',
    border: 'bottom',
    borderTone: 'subtle',
  },
  controlGroup: { flexLayout: 'column' },
  // Every group after the first is ruled off from the one above.
  controlGroupNext: {
    flexLayout: 'column',
    border: 'top',
    borderTone: 'subtle',
  },
  controlGrid: { flexLayout: 'column', paddingX: 5, paddingY: 2 },
  controlRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    minHeight: '44px',
    paddingY: 1,
  },
  controlLabel: { width: '128px', flexShrink: '0', minWidth: 0 },
  controlInput: { flexGrow: '1', minWidth: 0 },
  readOnly: {
    font: 'mono',
    textStyle: 'label',
    text: 'faint',
    wrap: 'anywhere',
  },
  empty: { paddingX: 5, paddingY: 4, textStyle: 'caption', text: 'faint' },

  // Source workbench.
  panel: {
    flexLayout: 'column',
    radius: '2xl',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    minWidth: 0,
    overflow: 'hidden',
  },
  panelBar: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 3,
    paddingX: 3,
    paddingY: 2.5,
    border: 'bottom',
    borderTone: 'subtle',
  },
  tabs: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 1 },
  fileName: {
    paddingRight: 2,
    font: 'mono',
    textStyle: 'label',
    text: 'faint',
  },
  panelBody: { flexLayout: 'column', gap: 4, padding: 5, minWidth: 0 },
  sheetPicker: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 3,
    paddingX: 5,
    paddingY: 3,
    textStyle: 'caption',
    weight: 'semibold',
    text: 'muted',
    border: 'bottom',
    borderTone: 'subtle',
  },
  source: { maxHeight: '560px', overflow: 'auto', minWidth: 0 },
  spread: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 3,
  },
  actions: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 2 },
  hint: { textStyle: 'caption', lineHeight: 1.6, text: 'muted' },
  editorLabel: { textStyle: 'caption', weight: 'semibold', text: 'default' },
  editor: {
    display: 'block',
    width: '100%',
    minHeight: '200px',
    padding: 4,
    radius: 'lg',
    fill: 'code',
    text: 'code',
    textStyle: 'code',
    border: 'all',
    borderTone: 'default',
    ':focus-visible': { borderTone: 'accent', elevation: 'focus-ring' },
    // No token: native <textarea> behaviour, and the ring replaces the outline.
    '@platform web': {
      $style: { resize: 'vertical', tabSize: 2, outline: 'none' },
    },
  },
  status: { textStyle: 'caption', lineHeight: 1.6, text: 'muted' },
  details: {
    flexLayout: 'column',
    gap: 2,
    textStyle: 'caption',
    text: 'muted',
  },
  summary: {
    cursor: 'pointer',
    radius: 'xs',
    weight: 'semibold',
    text: 'default',
  },
  detailBody: { flexLayout: 'column', gap: 1.5, paddingTop: 3 },
  token: { font: 'mono', textStyle: 'label', text: 'body', wrap: 'anywhere' },
  loading: { textStyle: 'caption', text: 'faint' },
  errorBanner: {
    paddingX: 4,
    paddingY: 3,
    radius: 'md',
    textStyle: 'caption',
    fill: 'danger-soft',
    text: 'danger-strong',
    border: 'all',
    borderTone: 'danger',
  },
}).variants(
  (
    $: Variants<{
      status: 'idle' | 'applied' | 'invalid'
      selected: boolean
    }>,
  ) => ({
    [$.selected(true)]: {
      themeOption: {
        text: 'accent-strong',
        fill: 'accent-soft',
        borderTone: 'accent',
      },
    },
    [$.status('applied')]: { status: { text: 'success' } },
    [$.status('invalid')]: {
      status: { text: 'danger' },
      editor: { borderTone: 'danger' },
    },
  }),
  { defaults: { status: 'idle', selected: false } },
)
