import type { Variants } from '@toned/core'

import { stylesheet } from './system.ts'

/**
 * Site search: the header trigger and the command palette it opens.
 *
 * The palette is a full-screen sheet on small screens and a centred panel
 * from `md` up. It has no entrance animation, so there is nothing to turn off
 * for reduced motion.
 */
export const searchStyles = stylesheet({
  // An icon button on small screens; a field-like button from `lg` up.
  Trigger: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    flexShrink: '0',
    width: 9,
    height: 9,
    radius: 'md',
    cursor: 'pointer',
    text: 'muted',
    fill: 'surface',
    border: 'all',
    borderTone: 'default',
    motion: 'colors',
    ':hover': { text: 'default', borderTone: 'strong' },
    '@media lg': {
      justifyContent: 'flex-start',
      width: '216px',
      paddingLeft: 3,
      paddingRight: 1.5,
    },
  },
  TriggerLabel: {
    display: 'none',
    flexGrow: '1',
    textStyle: 'ui',
    textAlign: 'left',
    '@media lg': { display: 'block' },
  },
  TriggerHint: { display: 'none', '@media lg': { display: 'flex' } },
  // A key cap, as in the code block chrome.
  Key: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 5,
    height: 5,
    paddingX: 1.5,
    radius: 'xs',
    font: 'sans',
    textStyle: 'label',
    weight: 'semibold',
    text: 'muted',
    fill: 'code-chrome',
    border: 'all',
    borderTone: 'default',
  },

  Overlay: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 60,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    font: 'sans',
    textStyle: 'body',
    text: 'default',
    '@media md': { paddingTop: 24, paddingX: 6 },
    // No token: the scrim behind a modal, the gallery's own overlay colour.
    '@platform web': { $style: { backgroundColor: '#17234b66' } },
  },
  Panel: {
    flexLayout: 'column',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    fill: 'surface',
    '@media md': {
      height: 'auto',
      maxHeight: '70vh',
      measure: 'copy',
      radius: 'xl',
      border: 'all',
      borderTone: 'default',
      elevation: 'panel',
    },
  },
  InputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    flexShrink: '0',
    height: 14,
    paddingLeft: 4,
    paddingRight: 3,
    text: 'faint',
    border: 'bottom',
    borderTone: 'subtle',
  },
  Input: {
    flexGrow: '1',
    minWidth: 0,
    height: '100%',
    textStyle: 'body',
    text: 'default',
    fill: 'none',
    border: 'none',
    // The field fills the row and always holds focus while the palette is
    // open, so the caret is the focus indicator; no outline around the row.
    '@platform web': { $style: { outline: 'none' } },
  },
  Close: {
    display: 'flex',
    alignItems: 'center',
    flexShrink: '0',
    height: 6,
    paddingX: 2,
    radius: 'sm',
    cursor: 'pointer',
    textStyle: 'label',
    weight: 'semibold',
    text: 'muted',
    fill: 'code-chrome',
    border: 'all',
    borderTone: 'default',
    motion: 'colors',
    ':hover': { text: 'default', borderTone: 'strong' },
  },
  List: {
    flexGrow: '1',
    minHeight: 0,
    overflowY: 'auto',
    paddingX: 2,
    paddingBottom: 2,
    // No token: keeps a finished list scroll from moving the page behind.
    '@platform web': { $style: { overscrollBehavior: 'contain' } },
  },
  GroupTitle: {
    paddingX: 3,
    paddingTop: 4,
    paddingBottom: 1.5,
    textStyle: 'overline',
    weight: 'heavy',
    text: 'faint',
  },
  Option: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    paddingX: 3,
    paddingY: 2,
    radius: 'md',
    cursor: 'pointer',
  },
  OptionIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: '0',
    width: 8,
    height: 8,
    radius: 'sm',
    font: 'mono',
    textStyle: 'ui',
    weight: 'semibold',
    text: 'faint',
    fill: 'sunken',
    border: 'all',
    borderTone: 'subtle',
  },
  OptionBody: { flexLayout: 'column', flexGrow: '1', minWidth: 0 },
  OptionTitle: {
    textStyle: 'ui',
    lineHeight: 1.5,
    weight: 'semibold',
    text: 'default',
    wrap: 'truncate',
  },
  OptionExcerpt: {
    textStyle: 'caption',
    lineHeight: 1.5,
    text: 'muted',
    wrap: 'truncate',
  },
  OptionPath: {
    textStyle: 'label',
    lineHeight: 1.5,
    text: 'faint',
    wrap: 'truncate',
  },
  // The Enter glyph, shown on the option the keyboard would open.
  OptionEnter: {
    display: 'none',
    flexShrink: '0',
    textStyle: 'ui',
    text: 'accent',
  },
  Mark: { text: 'accent-strong', fill: 'none', weight: 'bold' },
  Empty: {
    flexLayout: 'column',
    gap: 1,
    paddingX: 6,
    paddingY: 12,
    textAlign: 'center',
    textStyle: 'ui',
    text: 'muted',
  },
  EmptyTitle: { weight: 'semibold', text: 'default', wrap: 'anywhere' },
  Footer: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    flexShrink: '0',
    bar: 'code',
    paddingX: 4,
    textStyle: 'label',
    text: 'muted',
    fill: 'code-chrome',
    border: 'top',
    borderTone: 'subtle',
  },
  Hint: { display: 'flex', alignItems: 'center', gap: 1.5 },
  Status: { marginLeft: 'auto', wrap: 'nowrap', numeric: 'tabular' },
}).variants(($: Variants<{ active?: boolean }>) => ({
  [$.active(true)]: {
    Option: { fill: 'accent-soft' },
    OptionIcon: { text: 'accent', fill: 'surface', borderTone: 'accent-soft' },
    OptionEnter: { display: 'block' },
  },
}))
